export const EMERGENCY_CONTACTS_INDIA = [
  { number: "100", department: "Police" },
  { number: "101", department: "Fire" },
  { number: "102", department: "Ambulance" },
  { number: "103", department: "Traffic Police" },
  { number: "104", department: "State level Helpline for Health" },
  { number: "108", department: "Disaster Management / Medical Helpline" },
  { number: "112", department: "All in one Emergency Number" },
  { number: "131", department: "Indian Railway General Enquiry" },
  { number: "139", department: "Railway Enquiry" },
  { number: "181", department: "Domestic abuse and sexual violence - Women's Helpline" },
  { number: "197", department: "Directory enquiry service" },
  { number: "198", department: "Telephone Complaint Booking" },
  { number: "1031", department: "Anti Corruption Helpline" },
  { number: "1033", department: "Emergency Relief Centre on National Highways" },
  { number: "1066", department: "Anti-poison" },
  { number: "1071", department: "Air Accident" },
  { number: "1072", department: "Train accident" },
  { number: "1073", department: "Road Accident / Traffic Help Line" },
  { number: "1090", department: "Anti terror Helpline / Alert All India" },
  { number: "1091", department: "Women Helpline in Distress" },
  { number: "1092", department: "Earth-quake Help line service" },
  { number: "1096", department: "Natural Disaster Control Room" },
  { number: "1097", department: "AIDS Helpline" },
  { number: "1098", department: "Child Abuse Hotline" },
  { number: "1099", department: "Central Accident and Trauma Services" },
  { number: "1551", department: "Kisan Call Center" },
  { number: "1906", department: "LPG emergency helpline number" },
  { number: "1910", department: "Blood Bank Information" },
  { number: "1919", department: "Eye Donation / Eye bank information service" },
  { number: "1947", department: "Aadhar Card-UIDAI" },
  { number: "1950", department: "Election Commission of India" },
  { number: "1800-11-4000", department: "National Consumer Helpline" },
];

export const QUICK_EMERGENCY_CONTACTS = [
  { number: "112", department: "All in one Emergency Number" },
  { number: "100", department: "Police" },
  { number: "101", department: "Fire" },
  { number: "102", department: "Ambulance" },
  { number: "108", department: "Medical / Disaster Helpline" },
  { number: "181", department: "Women's Helpline" },
  { number: "1098", department: "Child Helpline" },
];
